import chalk from 'chalk';
import fs from 'node:fs';
import path from 'node:path';
import type { Session, WatchEvent } from './types.js';
import { loadSession } from './session.js';
import { verifySession } from './integrity.js';
import { banner, verifyDisplay } from './display.js';

function groupByRisk(events: WatchEvent[]): Record<string, WatchEvent[]> {
  return events.reduce((acc, event) => {
    if (!acc[event.risk]) acc[event.risk] = [];
    acc[event.risk].push(event);
    return acc;
  }, {} as Record<string, WatchEvent[]>);
}

function generateMarkdown(session: Session): string {
  const { summary, events } = session;
  const startDate = new Date(session.startTime).toLocaleString();
  const endDate = new Date(session.endTime).toLocaleString();

  const dangerEvents = events.filter(e => e.risk === 'danger');
  const cautionEvents = events.filter(e => e.risk === 'caution');

  // Verify integrity for compliance section
  const integrity = verifySession(session);

  let md = `# Unworldly Security Report

> Generated by [Unworldly](https://github.com/DilawarShafiq/unworldly) — The Flight Recorder for AI Agents
> ISO 42001 Compliant Audit Trail

## Session Overview

| Field | Value |
|-------|-------|
| Session ID | \`${session.id}\` |
| Version | \`${session.version}\` |
| Directory | \`${session.directory}\` |
| Started | ${startDate} |
| Ended | ${endDate} |
| Total Events | ${summary.totalEvents} |
| Risk Score | **${summary.riskScore}/10** |
${session.agent ? `| Agent | ${session.agent.name} (${session.agent.detectedVia}) |\n` : ''}
## Integrity Verification

| Check | Status |
|-------|--------|
| Hash Chain | ${integrity.validEvents}/${integrity.totalEvents} events verified |
| Session Seal | ${integrity.sessionHashValid ? 'Valid' : 'Invalid or missing'} |
| Overall | ${integrity.valid ? '**PASSED** — No tampering detected' : '**FAILED** — Possible tampering'} |
${integrity.errors.length > 0 ? `\n**Issues:**\n${integrity.errors.map(e => `- ${e}`).join('\n')}\n` : ''}
## Risk Breakdown

| Level | Count |
|-------|-------|
| Safe | ${summary.safe} |
| Caution | ${summary.caution} |
| Danger | ${summary.danger} |

`;

  if (dangerEvents.length > 0) {
    md += `## Dangerous Actions\n\n`;
    md += `| Time | Action | Target | Reason |\n`;
    md += `|------|--------|--------|--------|\n`;
    for (const e of dangerEvents) {
      const time = new Date(e.timestamp).toLocaleTimeString('en-US', { hour12: false });
      const action = e.type === 'command' ? 'COMMAND' : e.type.toUpperCase();
      md += `| ${time} | ${action} | \`${e.path}\` | ${e.reason || '-'} |\n`;
    }
    md += '\n';
  }

  if (cautionEvents.length > 0) {
    md += `## Caution Actions\n\n`;
    md += `| Time | Action | Target | Reason |\n`;
    md += `|------|--------|--------|--------|\n`;
    for (const e of cautionEvents) {
      const time = new Date(e.timestamp).toLocaleTimeString('en-US', { hour12: false });
      const action = e.type === 'command' ? 'COMMAND' : e.type.toUpperCase();
      md += `| ${time} | ${action} | \`${e.path}\` | ${e.reason || '-'} |\n`;
    }
    md += '\n';
  }

  // Commands Executed section
  const commandEvents = events.filter(e => e.type === 'command');
  if (commandEvents.length > 0) {
    md += `## Commands Executed\n\n`;
    md += `| # | Time | Command | Risk | Reason |\n`;
    md += `|---|------|---------|------|--------|\n`;
    commandEvents.forEach((e, i) => {
      const time = new Date(e.timestamp).toLocaleTimeString('en-US', { hour12: false });
      const risk = e.risk === 'danger' ? '🚨 DANGER'
        : e.risk === 'caution' ? '⚠️ Caution'
        : '✅ Safe';
      md += `| ${i + 1} | ${time} | \`${e.path}\` | ${risk} | ${e.reason || '-'} |\n`;
    });
    md += '\n';
  }

  md += `## Full Event Timeline\n\n`;
  md += `| # | Time | Action | Target | Risk |\n`;
  md += `|---|------|--------|--------|------|\n`;
  events.forEach((e, i) => {
    const time = new Date(e.timestamp).toLocaleTimeString('en-US', { hour12: false });
    const action = e.type === 'command' ? 'COMMAND' : e.type.toUpperCase();
    const risk = e.risk === 'danger' ? '🚨 DANGER'
      : e.risk === 'caution' ? '⚠️ Caution'
      : '✅ Safe';
    md += `| ${i + 1} | ${time} | ${action} | \`${e.path}\` | ${risk} |\n`;
  });

  md += `\n---\n*Report generated by Unworldly v${session.version}*\n`;

  return md;
}

export async function report(
  sessionPath: string,
  options: { output?: string; format?: string } = {},
): Promise<void> {
  const session = loadSession(sessionPath);
  const format = options.format ?? 'terminal';

  if (format === 'md' || format === 'markdown') {
    const markdown = generateMarkdown(session);
    const outputPath = options.output ?? `unworldly-report-${session.id}.md`;
    fs.writeFileSync(outputPath, markdown, 'utf-8');
    console.log(banner());
    console.log(chalk.green(`  Report saved: ${outputPath}`));
    console.log('');
    return;
  }

  // Terminal format
  console.log(banner());
  console.log(chalk.white.bold('  Security Report'));
  console.log('');

  const { summary } = session;
  const scoreColor = summary.riskScore >= 7
    ? chalk.red.bold
    : summary.riskScore >= 4
      ? chalk.yellow.bold
      : chalk.green.bold;

  console.log(`  Session:   ${chalk.white(session.id)}`);
  console.log(`  Directory: ${chalk.gray(session.directory)}`);
  console.log(`  Recorded:  ${chalk.gray(new Date(session.startTime).toLocaleString())}`);
  if (session.agent) {
    console.log(`  Agent:     ${chalk.cyan(session.agent.name)} ${chalk.gray(`(${session.agent.detectedVia})`)}`);
  }
  console.log('');

  // Integrity verification
  const integrity = verifySession(session);
  console.log(verifyDisplay(integrity));
  console.log(`  Risk Score: ${scoreColor(summary.riskScore + '/10')}`);
  console.log('');
  console.log(`  ${chalk.green('●')} Safe: ${summary.safe}  ${chalk.yellow('●')} Caution: ${summary.caution}  ${chalk.red('●')} Danger: ${summary.danger}`);
  console.log('');

  const dangerEvents = session.events.filter(e => e.risk === 'danger');
  const cautionEvents = session.events.filter(e => e.risk === 'caution');

  if (dangerEvents.length > 0) {
    console.log(chalk.red.bold('  Dangerous Actions:'));
    for (const e of dangerEvents) {
      const time = new Date(e.timestamp).toLocaleTimeString('en-US', { hour12: false });
      const action = e.type === 'command' ? '$> CMD' : e.type.toUpperCase();
      console.log(chalk.red(`    ${time}  ${action}  ${e.path}  — ${e.reason}`));
    }
    console.log('');
  }

  if (cautionEvents.length > 0) {
    console.log(chalk.yellow.bold('  Caution Actions:'));
    for (const e of cautionEvents) {
      const time = new Date(e.timestamp).toLocaleTimeString('en-US', { hour12: false });
      const action = e.type === 'command' ? '$> CMD' : e.type.toUpperCase();
      console.log(chalk.yellow(`    ${time}  ${action}  ${e.path}  — ${e.reason}`));
    }
    console.log('');
  }

  if (summary.riskScore >= 7) {
    console.log(chalk.red.bold('  ⚠ HIGH RISK SESSION — Review dangerous actions above'));
  } else if (summary.riskScore >= 4) {
    console.log(chalk.yellow('  Some concerning activity detected — review caution items'));
  } else {
    console.log(chalk.green('  Session looks clean — no major concerns'));
  }
  console.log('');

  // Suggest markdown export
  console.log(chalk.gray(`  Export full report: unworldly report ${sessionPath} --format md`));
  console.log('');
}
